### PR TITLE
Updated correct link to IETF draft

### PR DESCRIPTION
**Pull request by danehrlich1**
Updated correct link to IETF draft and also made it the latest version (06)

### CODE REVIEW

**Comment by joker314** [comment]
Thank you for the pull request. However, the current link is designed to automatically redirect to the latest version - so we don't have to change it every single time a new draft is released. Currently, it should be redirecting to the -06 version, but please let us know if it doesn't. 

Thanks again!

**Comment by danehrlich1** [comment]
It does not, but that could be my browser. can you give it a test on your side?

**Comment by joker314** [comment]
This link: https://tools.ietf.org/html/draft-foudil-securitytxt

It redirects for me. What happens when you try to open it?

**Comment by danehrlich1** [comment]
Works. Must have been the wifi. I had no cell signal earlier either, so couldn't confirm like I normally did. Kind of weird because when I googled that link wound up working (the one I used for the pull request). Anyway closing out.

**Pull request closed without merging**
